apiVersion: apps/v1
kind: Deployment
metadata:
  name: django-server
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: django-server
  template:
    metadata:
      labels:
        app: django-server
    spec:
      initContainers:
        - name: django-migrate
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: "{{ .Values.image.pullPolicy }}"
          command: [ "sh", "-c" ]
          args: [ "python manage.py migrate --noinput" ]
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: "{{ .Values.image.pullPolicy }}"
          ports:
            - containerPort: 8000
          env:
            {{- toYaml .Values.env | nindent 12 }}
